services:

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
#    profiles:
#      - local
    volumes:
      - ./my_chroma_db:/data

      
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres2
      POSTGRES_PASSWORD: postgres2
      POSTGRES_DB: postgres2
    ports:
      - "5433:5432"  # host:container mapping
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  api:
    build: ./
    depends_on:
      - chromadb
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:ro
    env_file:
      - ./.env

      
#   web:
#     build:
#       context: ./web
#       args:
#         NEXT_PUBLIC_API_URL: http://localhost:8000
#     ports:
#       - "3000:3000"
#     depends_on:
#       - api

  # streamlit:
  #   build: ./streamlit-app
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - api